
package ioservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IoServiceImplService", targetNamespace = "http://impl.service.spring.com/", wsdlLocation = "http://localhost:9000/IOservice?wsdl")
public class IoServiceImplService
    extends Service
{

    private final static URL IOSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException IOSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName IOSERVICEIMPLSERVICE_QNAME = new QName("http://impl.service.spring.com/", "IoServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/IOservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IOSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        IOSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public IoServiceImplService() {
        super(__getWsdlLocation(), IOSERVICEIMPLSERVICE_QNAME);
    }

    public IoServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IOSERVICEIMPLSERVICE_QNAME, features);
    }

    public IoServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, IOSERVICEIMPLSERVICE_QNAME);
    }

    public IoServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IOSERVICEIMPLSERVICE_QNAME, features);
    }

    public IoServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IoServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IoServiceImpl
     */
    @WebEndpoint(name = "IoServiceImplPort")
    public IoServiceImpl getIoServiceImplPort() {
        return super.getPort(new QName("http://impl.service.spring.com/", "IoServiceImplPort"), IoServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IoServiceImpl
     */
    @WebEndpoint(name = "IoServiceImplPort")
    public IoServiceImpl getIoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.spring.com/", "IoServiceImplPort"), IoServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IOSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw IOSERVICEIMPLSERVICE_EXCEPTION;
        }
        return IOSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
