
package ioservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IoServiceImpl", targetNamespace = "http://impl.service.spring.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IoServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://impl.service.spring.com/", className = "ioservice.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://impl.service.spring.com/", className = "ioservice.SayHelloResponse")
    @Action(input = "http://impl.service.spring.com/IoServiceImpl/sayHelloRequest", output = "http://impl.service.spring.com/IoServiceImpl/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<ioservice.Io>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://impl.service.spring.com/", className = "ioservice.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://impl.service.spring.com/", className = "ioservice.GetAllResponse")
    @Action(input = "http://impl.service.spring.com/IoServiceImpl/getAllRequest", output = "http://impl.service.spring.com/IoServiceImpl/getAllResponse")
    public List<Io> getAll();

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertOne", targetNamespace = "http://impl.service.spring.com/", className = "ioservice.InsertOne")
    @ResponseWrapper(localName = "insertOneResponse", targetNamespace = "http://impl.service.spring.com/", className = "ioservice.InsertOneResponse")
    @Action(input = "http://impl.service.spring.com/IoServiceImpl/insertOneRequest", output = "http://impl.service.spring.com/IoServiceImpl/insertOneResponse")
    public int insertOne(
        @WebParam(name = "arg0", targetNamespace = "")
        Io arg0);

}
